### ISSUE TITLE
[Bug Report] Play and Pause Button

### ISSUE THREAD

**Issue by kolung** [kishanankara/beautifulSoup#55]
Here is the picture of buttons in the playlist page. 

![e9789c8fde6d1967f932d6c2a5b074c5](https://user-images.githubusercontent.com/36254190/38860048-448b5d22-41fd-11e8-8e48-e24dd4e70f7f.png)

There should be only one pause button and the rest should be play button.

**Comment by yooil** [comment]
We are currently working on this problem. It will be fixed by next week.

**Comment by nlagrassa** [comment]
Fixed! Apologies for the delay in fixing this issue. We've had some trouble communicating with our front-end developer and it took me a while to learn the necessary skills to fix it. 

Just for the sake of clarity for the reader on what this issue was and was not referring to:
Tracks always automatically paused when a new track was selected for play.  This issue correctly refers to the problem that the play/pause buttons on previously clicked songs would not automatically toggle back to the "play" (triangle) state when a new song was selected for play. 

Play/pause buttons now toggle to correct image state (either double pipe or triangle) at all times, where there is only ever at most one song with a double pipe image display at a time.

(See merge #77 for code)
